WARNING:root:You are using solc version 0.5.17, The latest supported version is 0.4.19
incomplete push instruction at 1104
incomplete push instruction at 6265
incomplete push instruction at 1119
incomplete push instruction at 1106
incomplete push instruction at 148
INFO:root:contract /sb/0x7ad8f9ab85107fcb60e7423930adf00141fc9b39.sol:BPool:
INFO:symExec:	============ Results ===========
Traceback (most recent call last):
  File "/oyente/oyente/oyente.py", line 232, in <module>
    main()
  File "/oyente/oyente/oyente.py", line 227, in main
    exit_code = analyze_solidity()
  File "/oyente/oyente/oyente.py", line 110, in analyze_solidity
    results, exit_code = run_solidity_analysis(inputs)
  File "/oyente/oyente/oyente.py", line 87, in run_solidity_analysis
    result, return_code = symExec.run(disasm_file=inp['disasm_file'], source_map=inp['source_map'], source_file=inp['source'])
  File "/oyente/oyente/symExec.py", line 2458, in run
    analyze()
  File "/oyente/oyente/symExec.py", line 2441, in analyze
    run_build_cfg_and_analyze(timeout_cb=timeout_cb)
  File "/oyente/oyente/symExec.py", line 2398, in run_build_cfg_and_analyze
    build_cfg_and_analyze()
  File "/oyente/oyente/symExec.py", line 225, in build_cfg_and_analyze
    collect_vertices(tokens)
  File "/oyente/oyente/symExec.py", line 341, in collect_vertices
    idx = mapping_non_push_instruction(current_line_content, current_ins_address, idx, positions, length) if g_src_map else None
  File "/oyente/oyente/symExec.py", line 281, in mapping_non_push_instruction
    raise RuntimeError(F"Source map error, unknown name({name}) or instr_name({instr_name})")
RuntimeError: Source map error, unknown name(SHR) or instr_name(INVALID)
