class InternalError(Exception):
    pass

class SmartBugsError(Exception):
    pass
